application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000
---
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/online_course_management
    username: postgres
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    format:
      date: dd/MM/yyyy
      date-time: dd/MM/yyyy HH:mm:ss
      time: HH:mm:ss
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
---
springdoc:
  api-docs:
    enabled: true
    path: /swagger/docs
  swagger-ui:
    path: /swagger/ui.html
---
minio:
  url: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: my-bucket
---
server:
  port: 8089